version: "2"

linters:
  default: none
  enable:
  - dupword
  - godot
  - govet
  - ineffassign
  - misspell
  - revive
  - unused

  settings:
    govet:
      enable-all: true
      disable:
      - fieldalignment
      - shadow
    misspell:
      locale: US
    revive:
      severity: error
      enable-all-rules: true
      rules:
      - name: line-length-limit
        disabled: true
      - name: add-constant
        disabled: true
      - name: unchecked-type-assertion
        disabled: true

formatters:
  enable:
  - gofmt
  - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
