-- initial_schema (2025-11-29)

BEGIN;

CREATE TABLE IF NOT EXISTS threads (
  thread_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(100) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

END;
