name: Lint
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: read

jobs:
  go-mod:
    name: Check go.mod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Check go.mod
      run: |
        go mod tidy
        git diff --exit-code go.mod
        git diff --exit-code go.sum

  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.3.1
