name: Stop Radio

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  stop:
    name: Stop Radio
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Stop Radio
      run: |
        gcloud compute scp /tmp/yodahunters-deploy.tar.gz yodahunters:/tmp/yodahunters-deploy.tar.gz \
          --zone us-central1-a --tunnel-through-iap
        gcloud compute ssh yodahunters \
          --zone us-central1-a --tunnel-through-iap \
          --command '
            sudo tailscale serve off
            sudo tailscale down
            sudo systemctl icecast2 stop
            sudo cp ./config/Caddyfile /etc/caddy/Caddyfile
            sudo systemctl caddy reload
          '
